export const TEXTOS_EN = {

  // ==========================================
  // 1. ACCESSIBILITY AND SCREEN READERS
  // ==========================================
  acessibilidade: {
    areaAutenticacao: "Area reserved for system authentication",
    iniciarLeitura: "Text-to-speech started.",
    pararLeitura: "Text-to-speech stopped.",
    navegacaoBreadcrumb: "Structural navigation",
    saltarConteudo: "Skip to main content",
    botaoOuvir: "Listen to Text",
    botaoParar: "Stop Reading",
    tempoLeitura: "min read",
    ariaSidebar: "System lateral navigation",
    ariaToggleSidebar: "Toggle sidebar menu",
    ariaPerfil: "View my profile"
  },

  // ==========================================
  // 2. FOOTER
  // ==========================================
  footer: {
    ariaLabel: "Page footer",
    navSecundaria: "Secondary Navigation",
    sobreNos: "About us",
    mapaSite: "Sitemap",
    acessibilidade: "Accessibility",
    politicaPrivacidade: "Privacy Policy",
    telefone: "PHONE",
    numeroTelefone: "212 112 345",
    perguntas: "Frequently",
    frequentes: "Asked Questions",
    projetoIntegrador: "Capstone Project",
    direitosReservados: "Group 8. All rights reserved.",
    voltarAoTopo: "Back to top of the page",
    altPrr: "Logo of the Recovery and Resilience Plan of the Portuguese Republic",
    altUlisboa: "Logo of the University of Lisbon",
    altFcul: "Logo of the Faculty of Sciences of the University of Lisbon",
    altIpl: "Logo of the Lisbon Polytechnic Institute",
    altTecnico: "Logo of the Instituto Superior Técnico",
    altIsel: "Logo of the Lisbon Superior Institute of Engineering"
  },

  // ==========================================
  // 3. PUBLIC HEADER
  // ==========================================
  headerPublic: {
    linkInicio: "Go to SIAGUH homepage",
    altLogo: "SIAGUH system logo",
    titulo: "SIAGUH",
    subtitulo: "Integrated System for Hospital Emergency Management Support",
    botaoLogin: "Login"
  },

  // ==========================================
  // 4. GENERAL TEXTS (UTILITIES)
  // ==========================================
  geral: {
    inicio: "Home",
    voltar: "← Back",
    cancelar: "Cancel",
    guardar: "Save changes",
    editar: "Edit",
    erroGenerico: "An unexpected error occurred. Please try again.",
    pesquisarNome: "Search by name",
    pesquisarNumero: "Search by number",
    semResultados: "No results.",
    aCarregar: "Loading...",
    sim: "Yes",
    nao: "No",
    utilizador: "User",
    acoes: "Actions",
    sair: "Log Out"
  },

  // ==========================================
  // 5. ADMINISTRATOR PANEL
  // ==========================================
  admin: {
    tituloPainel: 'Administrator Panel',
    roleAdmin: 'Admin',
    roleMedico: 'Doctor',
    roleEnfermeiro: 'Nurse',
    roleRececionista: 'Receptionist',

    sexoMasculino: 'Male',
    sexoFeminino: 'Female',

    toggleMenu: 'Expand or collapse menu',
    irParaPerfil: 'Go to profile',
    botaoSair: 'Log out',

    menuUtilizadores: 'Users',
    menuFuncionarios: 'Employees',
    menuHospitais: 'Hospitals',
    menuRelatorios: 'Reports',

    descUtilizadores: 'Manage access accounts, pending accounts, and blocked users.',
    descFuncionarios: 'Manage employees, create new records, and assign hospitals.',
    descHospitais: 'List of existing hospitals and central panel editing.',
    descRelatorios: 'Activity summary and log history.',

    btnNovoUtilizador: 'New user',
    btnNovoFuncionario: 'New employee',
    btnNovoHospital: 'New hospital',
    btnBloquear: 'Block',
    btnDesbloquear: 'Unblock',
    btnAtualizar: 'Update',
    btnExportarDados: 'Export data',

    lblNome: 'Name',
    lblUsername: 'Username',
    lblPassword: 'Password',
    lblFuncao: 'Role',
    lblSexo: 'Gender',
    lblNumFuncionario: 'Employee No.',
    lblAcoes: 'Actions',
    lblHospitais: 'Hospitals',
    lblUtilizador: 'User',
    lblData: 'Date',
    lblLocalizacao: 'Location',
    lblEmail: 'Email',
    lblContacto: 'Contact',
    lblAssociarHospitais: 'Associate hospitals',
    lblGerirHospitaisAssociados: 'Manage associated hospitals',
    lblPesquisarLogs: 'Search (Action, Detail, User)',

    colData: 'Date',
    colAcao: 'Action',
    colDetalhe: 'Detail',

    placeholderPesquisarLogs: 'Type here...',
    placeholderPasswordOpcional: 'Leave empty to keep the current password',

    hospitaisDisponiveis: 'Available hospitals',
    hospitaisSelecionados: 'Selected hospitals',
    semHospitaisDisponiveis: 'No hospitals available.',
    nenhumHospitalSelecionado: 'No hospitals selected.',
    semLocalizacao: 'No location',
    adicionar: 'Add',
    remover: 'Remove',

    tblUtilizadoresComConta: 'Users with account',
    tblFuncionariosSemConta: 'Employees without account',
    tblUtilizadoresBloqueados: 'Blocked users',

    relTotalComConta: 'Total with account',
    relTotalRegistado: 'Total registered',

    todasFuncoes: 'All roles',
    semBloqueados: 'There are no blocked users.',
    semHistorico: 'No history.',

    sucessoCriarUser: 'User created successfully.',
    sucessoEditarUser: 'User updated successfully.',
    sucessoCriarFunc: 'Employee created successfully.',
    sucessoEditarFunc: 'Employee updated successfully.',
    sucessoCriarHosp: 'Hospital created successfully.',
    sucessoEditarHosp: 'Hospital updated successfully.',

    pesquisarHospital: "Search hospital",
    filtrarHospitais: "Filter hospitals"
  },

  // ==========================================
  // 6. ERRORS AND ACCESS DENIED
  // ==========================================
  acessoNegado: {
    label: "Access",
    titulo: "Access Denied",
    mensagem: "You do not have permissions to access this system area.",
    voltar: "Back to home",
    ariaVoltar: "Back to the system homepage"
  },

  // ==========================================
  // 7. PAGE: ABOUT US
  // ==========================================
  sobreNos: {
    tituloBreadcrumb: "About Us",
    heroTituloPrincipal: "About the",
    heroTituloDestaque: "Capstone Project",
    heroSubtitulo: "Group 8: Innovation, Fellowship, and Technical Excellence.",
    tituloEquipa: "The Team Behind the SIAGUH Project",
    ariaHero: "Initial project presentation",
    ariaHistoria: "Project history and development",
    ariaPararLeitura: "Stop reading aloud",
    ariaOuvirTexto: "Listen to this page's text",
    altFotoEquipa: "Photograph of Group 8 - The Frogs in an animated hospital environment",
    alertaSemSuporte: "Your browser does not support text-to-speech reading.",
    p1Texto: "The Capstone Project represents the strategic and technical culmination of a journey of high standards and innovation, materializing in the PRODIGI system. This Hospital Management software, focused on optimizing Emergencies and Inpatient care, merges robust systems architecture with clinical decision support powered by Artificial Intelligence. More than a simple digital tool, PRODIGI is the final result of months of dedication, where every line of code was designed to improve care efficiency and health data security.",
    p2Texto: "This project brought together four distinct backgrounds and visions into a single working group, Group 8, composed of João Martins, João Sacramento, Luís Franco, and Pedro Antunes. Throughout the development of this solution, what began as an academic collaboration evolved into an environment of strong fellowship and a solid friendship that went far beyond the laboratory walls. Together, these four members faced complex technical challenges, from database structuring to predictive model implementation, always keeping unity as their primary foundation.",
    p3Texto: "Reflecting the spirit of unity and good humor that characterized every meeting and work session, the group jokingly nicknamed themselves the 'Frogs' (Sapos). This internal code name symbolizes not only the agility and adaptability demonstrated when facing obstacles, but also the emotional bond created among everyone. PRODIGI is therefore more than a technological system of excellence; it is living proof that the success of a capstone project lies in the harmony and complicity of those who build it."
  },

  // ==========================================
  // 8. PAGE: ACCESSIBILITY STATEMENT
  // ==========================================
  acessibilidadePagina: {
    breadcrumb: "Accessibility",
    tituloPrincipal: "Accessibility and Usability Statement",
    introTexto1: "The ",
    grupo8: "Group 8",
    introTexto2: " commits to making the system website ",
    prodigi: "PRODIGI – SIAGUH",
    introTexto3: " available in accordance with Decree-Law No. 83/2018, of October 19, which transposes Directive (EU) 2016/2102 of the European Parliament and of the Council, regarding the accessibility of websites and mobile applications.",
    statusTitulo: "I. Compliance Status",
    statusTexto: "The SIAGUH website fully complies with Decree-Law No. 83/2018 of October 19.",
    elaboracaoTitulo: "II. Preparation of this Accessibility and Usability Statement",
    elaboracaoTexto: "This statement was updated on 17-04-2026. In accordance with current standards, the group adopted mandatory monitoring procedures.",
    avalAutoTitulo: "A. Automatic evaluations carried out (15-04-2026):",
    avalManualTitulo: "B. Manual evaluations carried out:",
    testesUsaTitulo: "C. Usability tests with users:",
    lblFerramenta: "Tool Used:",
    lblAmostra: "Sample:",
    lblResultados: "Main Results:",
    lblParticipantes: "Participant Profiling:",
    lblTarefas: "Tasks/Processes:",
    lblResponsaveis: "Responsible Parties:",
    lblEmail: "Email:",
    amostraWeb: "Main pages of the Web frontend (HTML5/CSS3/JS).",
    resAuto: "A high score was achieved, with most pages complying with WCAG 2.1 standards.",
    relManual: "(10-04-2026). Report: Functional Accessibility Checklist applied to SIAGUH modules.",
    amostraModulos: "Patient Registration, Triage, and Inpatient care screens.",
    resManual: "100% compliance within the heuristics applied to forms and navigation elements.",
    relUsa: "(20-03-2026). Report: SIAGUH Usability Tests.",
    participantesDesc: "Team members and external users simulating Clerk, Doctor, and Nurse profiles.",
    tarefasDesc: "Patient tracking, vital signs entry during triage, and consulting AI predictions.",
    resUsa: "The portal displays a robust level of usability, facilitating interactions even under critical hospital emergency scenarios.",
    contactoTitulo: "III. Contact and Request for Information Regarding the Website",
    contactoTexto: "To get in touch, send suggestions, or request additional information regarding the SIAGUH system functionalities developed by Group 8, please use the contacts of those responsible:",
    responsaveisNomes: "João Martins, João Sacramento, Luís Franco, and Pedro Antunes.",
    evidenciasTitulo: "IV. Other Evidence",
    evidenciasTexto: "Group 8 implemented a modular architecture in the backend (FastAPI) and frontend to ensure that future accessibility updates can be integrated without compromising system scalability.",
    denunciaTitulo: "V. Reporting Situations of Discrimination",
    denunciaTexto: "Whenever a person with a disability is subject to less favorable treatment that constitutes a discriminatory practice, they may file a complaint under current legislation. The National Institute for Rehabilitation (INR, I.P.) provides the competent channels for this purpose.",
    notaRodape: "This Statement was created for the PRODIGI Capstone Project (Group 8 - 2026) in compliance with Decree-Law No. 83/2018, of October 19.",
    seccaoIntro: "Accessibility and Usability Statement. The Group 8 Frogs commit to making the website of the PRODIGI Hospital Management System available in accordance with current legislation.",
    seccao1Voz: "Section 1. Compliance status. The PRODIGI website is fully compliant.",
    seccao2Voz: "Section 2. Preparation of this declaration. This declaration was updated in April 2026.",
    seccaoA_Voz: "Point A. Automatic evaluations. A high score was achieved within WCAG 2.1 standards.",
    seccaoB_Voz: "Point B. Manual evaluations. 100% compliance in heuristics applied to forms.",
    seccaoC_Voz: "Point C. Usability tests. The portal showcases a robust level of usability in critical scenarios.",
    seccao3Voz: "Section 3. Contact. Use the email group 8 underscore prodigi at exemplo dot pt.",
    seccao4Voz: "Section 4. Other evidence. Modular architecture implemented to ensure scalability and future updates.",
    seccao5Voz: "Section 5. Reporting. The National Institute for Rehabilitation provides channels for discrimination complaints."
  },

  // ==========================================
  // 9. PAGE: FAQS
  // ==========================================
  faqs: {
    titulo: "Frequently Asked Questions (FAQs)",
    subtitulo: "Find quick answers to the most common questions about how the SIAGUH system works.",
    expandirTudo: "Expand all",
    colapsarTudo: "Collapse all",
    q1: "What is SIAGUH?",
    a1: "It is the Integrated System for Hospital Emergency Management Support, a modular platform (SIAGUH) developed to manage workflow from patient admission to discharge or hospitalization.",
    q2: "Is my data secure?",
    a2: "Yes. The system utilizes robust authentication (JWT) and complies with GDPR rules to ensure that only authorized professionals access clinical records.",
    q3: "How is my wristband color decided?",
    a3: "The nurse enters your vital signs and symptoms into the system. Our AI analyzes this data alongside the patient's medical history and suggests a color based on the Manchester Triage Protocol, but the final decision is always validated by a healthcare professional.",
    q4: "Is the displayed wait time exact?",
    a4: "The time is an estimate calculated by the AI based on the hospital's historical data, active staff framework, and the number of patients currently waiting. It may change if critical emergency cases arise (red wristbands).",
    q5: "How do I know which room I am hospitalized in?",
    a5: "This information is managed within the inpatient module, where the system automatically assigns a bed and ward following the clinical decision.",
    q6: "Where can I check my prescriptions?",
    a6: "Prescriptions issued by doctors are logged into your clinical history within SIAGUH and can be consulted by any of the professionals tracking your care.",
    q7: "How do I recover my employee access?",
    a7: "You must contact the system Administrator, who is responsible for account and permission management within the professionals module.",
    q8: "Does the system work on mobile devices?",
    a8: "Yes, SIAGUH has a dedicated Android application so that professionals can check data and record medical acts on the go."
  },

  // ==========================================
  // 10. PAGE: HOME (LANDING PAGE - CORE)
  // ==========================================
  home: {
    labelIntro: "Introduction",
    tituloPrincipal: "SIAGUH — Integrated System for Hospital Emergency Management Support",
    subtituloPrincipal: "Support platform for hospital management, emergencies, inpatient care, and healthcare professionals organization.",
    labelProjeto: "Project",
    valorProjeto: "Group 8 · PRODIGI",
    labelArea: "Area",
    valorArea: "Emergencies and inpatient care",
    labelTech: "Technology",
    valorTech: "FastAPI · PostgreSQL · Docker",
    labelHospitais: "Hospitals",
    tituloHospitais: "Available hospitals and wait times",
    subtituloHospitais: "Quick consultation of units registered within the system.",
    statusDisponivel: "Available",
    labelEspera: "Wait time",
    valorEsperaIndisponivel: "-- min",
    btnAnterior: "View previous hospitals",
    btnSeguinte: "View next hospitals",
    ariaPaginacao: "Navigation between hospital pages",
    ariaDots: "Hospital page indicator",
    labelInfo: "More information",
    tituloInfo: "Highlights and Information",
    ariaCarrossel: "System information highlights",
    altSlide: "Highlight information number",
    ariaIrParaSlide: "Go to slide",
    heroEyebrow: "Health Portal",
    heroTitle: "Wait times and health information in a single place.",
    heroDescription: "Monitor hospitals, check real-time predictions, and quickly find the most relevant information with a clear, modern, and professional experience.",
    btnConsultarHospitais: "Consult hospitals",
    btnVerInformacoes: "View information",
    liveStatus: "Real time",
    liveSubStatus: "Automatically updated",
    statProjetoLabel: "Project",
    statProjetoNote: "Integrated management and user support system.",
    statAreaLabel: "Area",
    statAreaValue: "Health",
    statAreaNote: "Useful information for quick and safe decisions.",
    statTecnologiaLabel: "Technology",
    statTecnologiaNote: "Wait time predictions and real-time visualization.",
    statAtualizacaoLabel: "Update",
    statAtualizacaoValue: "Automatic",
    statMediaEstimada: "Current estimated average:",
    trustTempoRealTitle: "Real time",
    trustTempoRealText: "Quick consultation with continuous updates.",
    trustIaTitle: "Predictive AI",
    trustIaText: "Data-driven estimations.",
    trustCoberturaTitle: "Coverage",
    trustCoberturaText: "Active hospitals:",
    trustConfiancaTitle: "Trust",
    trustConfiancaText: "Clean, clear, and user-centered layout.",
    seccaoHospitaisTitle: "Hospitals",
    seccaoHospitaisSubtitle: "Results organized for quick reading, with immediate access to details.",
    placeholderPesquisa: "Search hospital...",
    nenhumHospitalEncontrado: "No hospitals found.",
    seccaoInfoTitle: "Additional information",
    altImagemAdicional: "Additional information",
    ariaSlide: "Slide",
    statusAtivo: "Active",
    statusIndisponivel: "Unavailable",
    unidadeMinutos: "min",
    erroSincronizacao: "Could not connect to the SIAGUH server. Ensure the backend is running and authenticated.",
    ariaVerDetalhes: "View details"
  },

  // ==========================================
  // 11. PAGE: LOGIN (CORE)
  // ==========================================
  login: {
    tituloLogin: "Login",
    subtituloLogin: "Enter your credentials to log into the system.",
    tituloHospital: "Select hospital",
    subtituloHospital: "Choose the hospital where you will work during this session.",
    labelPasso1: "Authentication",
    labelPasso2: "Hospital",
    btnEntrar: "Log In",
    erroLogin: "Error trying to log in.",
    erroRole: "User role not identified.",
    erroHospitais: "This user has no authorized hospitals.",
    erroDestino: "Could not determine destination page.",
    ariaVoltar: "Back to homepage",
    ariaPassoHospital: "Correct credentials. Now, select a hospital from the list below.",
    brandTitle: "Smart management for hospital emergencies.",
    brandDescription: "Access the platform to manage patient care, triage, clinical episodes, and hospital operations with greater speed and control.",
    chipLiveTitle: "Real time",
    chipLiveText: "Centralized queues, statuses, and hospital context.",
    chipRolesTitle: "Profile access",
    chipRolesText: "Dedicated workflows for administration, reception, nursing, and medicine.",
    labelPasso1: "Step 1 of 2",
    labelPasso2: "Step 2 of 2",
    termoHospital: "Hospital"
  },

  // ==========================================
  // 12. PAGE: PRIVACY POLICY
  // ==========================================
  politicaPrivacidade: {
    breadcrumb: "Privacy Policy",
    tituloPrincipal: "Privacy Policy — SIAGUH",
    notaLabel: "Note:",
    notaTexto: "This system was developed for academic purposes by Group 8 (João Martins, João Sacramento, Luís Franco, and Pedro Antunes).",
    s1Titulo: "1. General Framework",
    s1Texto1: "This Privacy Policy applies to ",
    s1Texto2: " including the web portal, Android mobile application, and triage systems developed by Group 8 within the scope of the 2026 Capstone Project.",
    s2Titulo: "2. Data Controller and Data Protection Officer",
    s2Texto: "The data controller is Group 8, under academic supervision within the scope of the PRODIGI/SIAGUH project.",
    s3Titulo: "3. Personal Data Processed",
    s3Intro: "SIAGUH collects and processes data necessary for secure hospital operations:",
    lblDemog: "Demographic Data:",
    txtDemog: "Name, date of birth, NIF, patient number, city, and contacts.",
    lblSaude: "Health Data:",
    txtSaude: "Symptoms, clinical history, triage records, medical acts, and prescriptions.",
    lblIA: "AI Data:",
    txtIA: "Results from natural language processing and forecasting algorithms.",
    s4Titulo: "4. Purposes and Legal Grounds",
    s4Intro: "Data processing within SIAGUH is grounded on the management and provision of healthcare services.",
    lblTriagem: "Clinical Triage:",
    txtTriagem: "Utilization of AI to suggest the wristband color.",
    lblDecisao: "Decision Support:",
    txtDecisao: "Predicting wait times and managing bed allocation.",
    lblSeguranca: "Security:",
    txtSeguranca: "Authentication of professionals via JWT.",
    s5Titulo: "5. Use of Artificial Intelligence in SIAGUH",
    s5Intro: "SIAGUH integrates an AI system to assist triage operations.",
    s5Item1: "The AI does not make autonomous decisions.",
    s5Item2: "The human user can always validate or ignore suggestions.",
    s5Item3: "The data gathered improves care precision.",
    s6Titulo: "6. Retention Period and Communication",
    lblConserva: "Retention:",
    txtConserva: "Maintained for the period strictly necessary for healthcare provision.",
    lblComunica: "Communication:",
    txtComunica: "Shared among professionals and authorized entities.",
    s7Titulo: "7. Data Subject Rights",
    s7Intro: "Patients and professionals enjoy the rights provided under the GDPR.",
    lblDireito1: "Access and Rectification:",
    txtDireito1: "(clinical history).",
    lblDireito2: "Objection to Automated Decisions:",
    txtDireito2: "Review requested from a human.",
    lblDireito3: "Portability:",
    txtDireito3: "Structured format.",
    s8Titulo: "8. Update and Jurisdiction",
    s8Texto: "This policy was updated on April 17, 2026.",
    v1: "SIAGUH Privacy Policy. Section 1. General Framework.",
    v2: "Section 2. Data Controller.",
    v3: "Section 3. Personal Data Processed.",
    v4: "Section 4. Purposes.",
    v5: "Section 5. Use of Artificial Intelligence.",
    v6: "Section 6. Data Retention.",
    v7: "Section 7. Data Subject Rights.",
    v8: "Section 8. Jurisdiction."
  },

  // ==========================================
  // 13. PAGE: EMPLOYEE PROFILE
  // ==========================================
  perfil: {
    titulo: "My Profile",
    sucessoGuardar: "Profile updated successfully!",
    erroCarregar: "Could not load your data: ",
    erroSessao: "User not found within the session.",
    erroGuardar: "Error saving: ",
    aCarregar: "Loading your profile...",
    botaoGuardar: "Save Changes",
    botaoGuardarLoading: "Saving...",
    numFuncionario: "Employee No.:",
    linkFotografia: "Profile Picture Link",
    placeholderFotografia: "https://...",
    telemovel: "Mobile Phone",
    emailPessoal: "Personal Email",
    sobreMim: "About Me",
    placeholderBiografia: "Write a brief description here about your professional experience...",
    segurancaAcesso: "Access Security",
    nomeUtilizador: "Username",
    novaPassword: "New Password",
    placeholderPassword: "(Leave blank to keep current)"
  },

  // ==========================================
  // 14. DASHBOARD: DOCTOR
  // ==========================================
  doctor: {
    tituloPainel: 'Doctor Dashboard',
    descricaoPainel: 'Priority, full clinical details, prescription, and final disposition.',
    menuKpis: 'KPIs',
    menuMedias: 'Average times',
    menuFila: 'Queue by priority',
    menuEpisodios: 'Triaged episodes',
    menuDetalhe: 'Full details',
    menuPrescricao: 'Prescription',
    menuAlta: 'Discharge / Admission',
    kpisTitulo: 'Clinical Summary',
    kpisDesc: 'Quick view of triaged episodes and current status.',
    episodiosTriados: 'Triaged episodes',
    emEspera: 'Waiting',
    altasHoje: 'Discharges today',
    internamentos: 'Hospitalizations',
    temposMedios: 'Average times by color tier',
    cor: 'Color',
    tempoMedio: 'Average time',
    filaPrioridade: 'Summary queue by priority',
    placeholderPesquisa: 'Patient, color, episode...',
    episodios: 'Episodes',
    utente: 'Patient',
    espera: 'Waiting time',
    acao: 'Action',
    atender: 'Attend',
    episodiosTriadosLista: 'Triaged episodes list',
    listaCompleta: 'Full list',
    episodio: 'Episode',
    gravidade: 'Severity',
    abrirDetalhe: 'Open details',
    detalheCompleto: 'Full episode breakdown details',
    alertas: 'Alerts',
    semAlertas: 'No recorded alerts.',
    medicacaoAtiva: 'Active medication',
    semMedicacao: 'No active medication.',
    selecionaTriado: 'Please select a triaged episode.',
    prescricao: 'Prescription',
    medicamento: 'Medication',
    dosagem: 'Dosage',
    duracao: 'Duration',
    via: 'Route',
    fazerPrescricao: 'Issue prescription',
    altaInternamento: 'Discharge or Hospitalization',
    destino: 'Disposition',
    alta: 'Discharge',
    destinoInternamento: 'Inpatient destination ward',
    observacoes: 'Observations',
    confirmar: 'Confirm',
  },

  // ==========================================
  // 15. DASHBOARD: NURSE
  // ==========================================
  nurse: {
    tituloPainel: 'Nurse Dashboard',
    descricaoPainel: 'Episode queue, clinical context, and assisted triage.',
    menuFila: 'Untriaged queue',
    menuTriagem: 'Open triage',
    menuFicha: 'Patient file',
    menuMedicacao: 'Active medication',
    menuRegisto: 'Record triage',
    filaSemTriagem: 'Open episodes queue without triage',
    placeholderPesquisa: 'Patient, NIF, episode...',
    episodios: 'Episodes',
    episodio: 'Episode',
    utente: 'Patient',
    entrada: 'Admission time',
    abrir: 'Open',
    abrirTriagem: 'Open episode for triage operation',
    verFicha: 'View file',
    verMedicacao: 'View medication',
    selecionaFila: 'Select an episode from the queue.',
    fichaUtente: 'Patient file record',
    nome: 'Name',
    dataNascimento: 'Date of birth',
    alergias: 'Allergies',
    abreEpisodioFicha: 'Open an episode to consult the patient file.',
    medicacaoAtiva: 'Active medication records',
    lista: 'List',
    posologia: 'Dosage instructions',
    inicio: 'Start',
    fim: 'End',
    registarTriagem: 'Record triage variables',
    tensao: 'Blood pressure',
    pulso: 'Pulse rate',
    temperatura: 'Temperature',
    saturacao: 'Oxygen saturation',
    dor: 'Pain scale',
    sintomas: 'Symptoms description',
    corSugerida: 'Suggested color tier',
    pedirSugestaoIa: 'Request AI suggestion',
    gravarTriagem: 'Save triage results',
  },

  // ==========================================
  // 16. DASHBOARD: RECEPTIONIST
  // ==========================================
  receptionist: {
    tituloPainel: 'Receptionist Dashboard',
    descricaoPainel: 'Patient management and emergency admission episodes.',
    menuPesquisar: 'Search patient',
    menuEpisodio: 'Open episode',
    menuRecentes: 'Recent admissions',
    pesquisarUtente: 'Search patient directory',
    novoUtente: 'New patient registration',
    pesquisaRapida: 'Quick search',
    placeholderPesquisa: 'Name, NIF, patient number...',
    utentes: 'Patients',
    nome: 'Name',
    nif: 'NIF',
    sexo: 'Gender',
    verFicha: 'View file',
    nenhumUtente: 'No patients found.',
    dataNascimento: 'Date of birth',
    telefone: 'Phone',
    email: 'Email',
    morada: 'Address',
    fichaBase: 'Base patient file',
    selecionaUtente: 'Select a patient from the search results.',
    abrirEpisodioBtn: 'Open admission episode',
    motivo: 'Reason for admission',
    observacao: 'Observation notes',
    utente: 'Patient',
    selecionaPrimeiro: 'Please select a patient first.',
    episodiosRecentes: 'Recent episodes log',
    pesquisaEpisodios: 'Quick search episodes',
    placeholderEpisodios: 'Search by name or state...',
    entrada: 'Admission',
    estado: 'Status',
    estadoAberto: 'Open',
    semEpisodios: 'No recent episodes found.',
    erroCarga: 'Error fetching data from server.',
    erroProcessamento: 'Error processing patient entity data.',
    erroEpisodio: 'Error opening admission episode.',
    sucessoCriar: 'Patient entity created successfully.',
    sucessoUpdate: 'Patient record updated successfully.',
    sucessoEpisodio: 'Admission episode opened successfully.',
    ariaSidebar: "Receptionist lateral navigation",
    ariaToggleSidebar: "Toggle sidebar menu",
    ariaPerfil: "View my professional profile"
  },

  // ==========================================
  // 17. PAGE: HOSPITAL DETAIL
  // ==========================================
  hospitalDetalhe: {
    erroCarregamento: "Could not load detailed data for this hospital.",
    naoEncontrado: "Hospital not found.",
    semLocalizacaoDefinida: "Location information available on the hospital file.",
    tituloInfoGeral: "General information",
    linkGoogleMaps: "Open in Google Maps ↗",
    labelEmail: "Email",
    labelTelefone: "Phone",
    labelMorada: "Address",
    valorNaoDisponivel: "Not available",
    tituloTriagem: "Wait times by triage tier",
    triagemVermelho: "Red",
    triagemLaranja: "Orange",
    triagemAmarelo: "Yellow",
    triagemVerde: "Green",
    triagemAzul: "Blue",
    tituloLocalizacao: "Location",
    iframeMapaDe: "Map of",
    btnVerRota: "View route on Google Maps →"
  }
};