export const TEXTOS_PT = {

  // ==========================================
  // 1. ACESSIBILIDADE E LEITORES DE ECRÃ
  // ==========================================
  acessibilidade: {
    areaAutenticacao: "Área reservada à autenticação no sistema",
    iniciarLeitura: "Leitura em voz alta iniciada.",
    pararLeitura: "Leitura em voz alta parada.",
    navegacaoBreadcrumb: "Navegação estrutural",
    saltarConteudo: "Saltar para o conteúdo principal",
    botaoOuvir: "Ouvir Texto",
    botaoParar: "Parar Leitura",
    tempoLeitura: "min de leitura",
    ariaSidebar: "Navegação lateral do sistema",
    ariaToggleSidebar: "Alternar menu lateral",
    ariaPerfil: "Ver meu perfil"
  },

  // ==========================================
  // 2. RODAPÉ (FOOTER)
  // ==========================================
  footer: {
    ariaLabel: "Rodapé da página",
    navSecundaria: "Navegação Secundária",
    sobreNos: "Sobre nós",
    mapaSite: "Mapa do Site",
    acessibilidade: "Acessibilidade",
    politicaPrivacidade: "Política de Privacidade",
    telefone: "TELEFONE",
    numeroTelefone: "212 112 345",
    perguntas: "Perguntas",
    frequentes: "Frequentes",
    projetoIntegrador: "Projeto Integrador",
    direitosReservados: "Grupo 8. Todos os direitos reservados.",
    voltarAoTopo: "Voltar ao topo da página",
    altPrr: "Logótipo do Plano de Recuperação e Resiliência da República Portuguesa",
    altUlisboa: "Logótipo da Universidade de Lisboa",
    altFcul: "Logótipo da Faculdade de Ciências da Universidade de Lisboa",
    altIpl: "Logótipo do Instituto Politécnico de Lisboa",
    altTecnico: "Logótipo do Instituto Superior Técnico",
    altIsel: "Logótipo do Instituto Superior de Engenharia de Lisboa"
  },

  // ==========================================
  // 3. CABEÇALHO PÚBLICO (HEADER PUBLIC)
  // ==========================================
  headerPublic: {
    linkInicio: "Ir para a página inicial do SIAGUH",
    altLogo: "Logótipo do sistema SIAGUH",
    titulo: "SIAGUH",
    subtitulo: "Sistema Integrado de Apoio à Gestão de Urgências Hospitalares",
    botaoLogin: "Login"
  },

  // ==========================================
  // 4. TEXTOS GERAIS (UTILITÁRIOS)
  // ==========================================
  geral: {
    inicio: "Início",
    voltar: "← Voltar",
    cancelar: "Cancelar",
    guardar: "Guardar alterações",
    editar: "Editar",
    erroGenerico: "Ocorreu um erro inesperado. Tente novamente.",
    pesquisarNome: "Pesquisar por nome",
    pesquisarNumero: "Pesquisar por número",
    semResultados: "Sem resultados.",
    aCarregar: "A carregar...",
    sim: "Sim",
    nao: "Não",
    utilizador: "Utilizador",
    acoes: "Ações",
    sair: "Sair"
  },

  // ==========================================
  // 5. PAINEL DE ADMINISTRAÇÃO
  // ==========================================

  admin: {
    tituloPainel: 'Painel de Administração',
    roleAdmin: 'Admin',
    roleMedico: 'Médico',
    roleEnfermeiro: 'Enfermeiro',
    roleRececionista: 'Rececionista',

    sexoMasculino: 'Masculino',
    sexoFeminino: 'Feminino',

    toggleMenu: 'Expandir ou recolher menu',
    irParaPerfil: 'Ir para o perfil',
    botaoSair: 'Terminar sessão',

    menuUtilizadores: 'Utilizadores',
    menuFuncionarios: 'Funcionários',
    menuHospitais: 'Hospitais',
    menuRelatorios: 'Relatórios',

    descUtilizadores: 'Gerir contas de acesso, contas pendentes e utilizadores bloqueados.',
    descFuncionarios: 'Gerir funcionários, criar novos registos e atribuir hospitais.',
    descHospitais: 'Lista de hospitais existentes e edição no painel central.',
    descRelatorios: 'Resumo de atividade e histórico.',

    btnNovoUtilizador: 'Novo utilizador',
    btnNovoFuncionario: 'Novo funcionário',
    btnNovoHospital: 'Novo hospital',
    btnBloquear: 'Bloquear',
    btnDesbloquear: 'Desbloquear',
    btnAtualizar: 'Atualizar',
    btnExportarDados: 'Exportar dados',

    lblNome: 'Nome',
    lblUsername: 'Username',
    lblPassword: 'Palavra-passe',
    lblFuncao: 'Função',
    lblSexo: 'Sexo',
    lblNumFuncionario: 'N.º Funcionário',
    lblAcoes: 'Ações',
    lblHospitais: 'Hospitais',
    lblUtilizador: 'Utilizador',
    lblData: 'Data',
    lblLocalizacao: 'Localização',
    lblEmail: 'Email',
    lblContacto: 'Contacto',
    lblAssociarHospitais: 'Associar hospitais',
    lblGerirHospitaisAssociados: 'Gerir hospitais associados',
    lblPesquisarLogs: 'Pesquisar (Ação, Detalhe, Utilizador)',

    colData: 'Data',
    colAcao: 'Ação',
    colDetalhe: 'Detalhe',

    placeholderPesquisarLogs: 'Escreve aqui...',
    placeholderPasswordOpcional: 'Deixa vazio para manter a password atual',

    hospitaisDisponiveis: 'Hospitais disponíveis',
    hospitaisSelecionados: 'Hospitais selecionados',
    semHospitaisDisponiveis: 'Sem hospitais disponíveis.',
    nenhumHospitalSelecionado: 'Nenhum hospital selecionado.',
    semLocalizacao: 'Sem localização',
    adicionar: 'Adicionar',
    remover: 'Remover',

    tblUtilizadoresComConta: 'Utilizadores com conta',
    tblFuncionariosSemConta: 'Funcionários sem conta',
    tblUtilizadoresBloqueados: 'Utilizadores bloqueados',

    relTotalComConta: 'Total com conta',
    relTotalRegistado: 'Total registado',

    todasFuncoes: 'Todas as funções',
    semBloqueados: 'Não existem utilizadores bloqueados.',
    semHistorico: 'Sem histórico.',

    sucessoCriarUser: 'Utilizador criado com sucesso.',
    sucessoEditarUser: 'Utilizador atualizado com sucesso.',
    sucessoCriarFunc: 'Funcionário criado com sucesso.',
    sucessoEditarFunc: 'Funcionário atualizado com sucesso.',
    sucessoCriarHosp: 'Hospital criado com sucesso.',
    sucessoEditarHosp: 'Hospital atualizado com sucesso.',

    pesquisarHospital: "Search hospital",
    filtrarHospitais: "Filter hospitals",
    hospitaisDisponiveis: "Available hospitals",
    hospitaisSelecionados: "Selected hospitals"
  },

  // ==========================================
  // 6. ERROS E ACESSO NEGADO
  // ==========================================
  acessoNegado: {
    label: "Acesso",
    titulo: "Sem permissão",
    mensagem: "Não tem permissões para aceder a esta área do sistema.",
    voltar: "Voltar ao início",
    ariaVoltar: "Voltar para a página inicial do sistema"
  },

  // ==========================================
  // 7. PÁGINA: SOBRE NÓS
  // ==========================================
  sobreNos: {
    tituloBreadcrumb: "Sobre Nós",
    heroTituloPrincipal: "Sobre o Projeto",
    heroTituloDestaque: "Integrador",
    heroSubtitulo: "Grupo 8: Inovação, Companheirismo e Excelência Técnica.",
    tituloEquipa: "A Equipa por trás do Projeto SIAGUH",
    ariaHero: "Apresentação inicial do projeto",
    ariaHistoria: "História e desenvolvimento do projeto",
    ariaPararLeitura: "Parar leitura em voz alta",
    ariaOuvirTexto: "Ouvir o texto desta página",
    altFotoEquipa: "Fotografia do Grupo 8 - Os Sapos em ambiente hospitalar animado",
    alertaSemSuporte: "O seu navegador não suporta a leitura de texto em voz alta.",
    p1Texto: "O Projeto Integrador surge como o culminar estratégico e técnico de um percurso de exigência e inovação, materializando-se no sistema PRODIGI. Este software de Gestão Hospitalar, focado na otimização de Urgências e Internamentos, representa a fusão entre a arquitetura de sistemas robustos e o apoio à decisão clínica através de Inteligência Artificial. Mais do que uma simples ferramenta digital, o PRODIGI é o resultado final de meses de dedicação, onde cada linha de código foi pensada para melhorar a eficiência do atendimento e a segurança dos dados de saúde.",
    p2Texto: "Este projeto uniu quatro percursos e visões num só grupo de trabalho, o Grupo 8, composto por João Martins, João Sacramento, Luís Franco e Pedro Antunes. Ao longo do desenvolvimento desta solução, o que começou por ser uma colaboração académica transformou-se num ambiente de forte companheirismo e de uma amizade sólida que ultrapassou os limites do laboratório. Juntos, estes quatro integrantes enfrentaram desafios técnicos complexos, desde a estruturação da base de dados até à implementação de modelos preditivos, mantendo sempre a união como o seu pilar principal.",
    p3Texto: "Refletindo o espírito de união e a boa disposição que caracterizou cada reunião e sessão de trabalho, o grupo acabou por se autoapelidar, em tom de brincadeira, de Sapos. Este nome de código interno simboliza não só a agilidade e a capacidade de adaptação demonstrada perante os obstáculos, mas também o laço afetivo que se criou entre todos. O PRODIGI é, por isso, mais do que um sistema tecnológico de excelência; é a prova viva de que o sucesso de um projeto integrador reside na harmonia e na cumplicidade daqueles que o constroem."
  },

  // ==========================================
  // 8. PÁGINA: DECLARAÇÃO DE ACESSIBILIDADE
  // ==========================================
  acessibilidadePagina: {
    breadcrumb: "Acessibilidade",
    tituloPrincipal: "Declaração de Acessibilidade e Usabilidade",
    introTexto1: "O",
    grupo8: "Grupo 8",
    introTexto2: "compromete-se a disponibilizar o sítio Web do sistema",
    prodigi: "PRODIGI – SIAGUH",
    introTexto3: "em conformidade com o Decreto-Lei n.º 83/2018, de 19 de outubro, que transpõe a Diretiva (UE) 2016/2102 do Parlamento e do Conselho Europeu, relativa à acessibilidade dos sítios Web e das aplicações móveis.",
    statusTitulo: "I. Estado de Conformidade",
    statusTexto: "O sítio Web SIAGUH está em conformidade com o Decreto-Lei n.º 83/2018 de 19 de outubro.",
    elaboracaoTitulo: "II. Elaboração da Presente Declaração de Acessibilidade e Usabilidade",
    elaboracaoTexto: "Esta declaração foi atualizada a 17-04-2026. De acordo com as normas vigentes e o grupo adotou os procedimentos de monitorização obrigatórios.",
    avalAutoTitulo: "A. Avaliações automáticas levadas a efeito (15-04-2026):",
    avalManualTitulo: "B. Avaliações manuais levadas a efeito:",
    testesUsaTitulo: "C. Testes de usabilidade com utilizadores:",
    lblFerramenta: "Ferramenta Utilizada:",
    lblAmostra: "Amostra:",
    lblResultados: "Principais Resultados:",
    lblParticipantes: "Caracterização dos Participantes:",
    lblTarefas: "Tarefas/Processos:",
    lblResponsaveis: "Responsáveis:",
    lblEmail: "Correio Eletrónico:",
    amostraWeb: "Páginas principais do frontend Web (HTML5/CSS3/JS).",
    resAuto: "Foi obtido um score elevado, com a maioria das páginas em conformidade com as normas WCAG 2.1.",
    relManual: "(10-04-2026). Relatório: Checklist de Acessibilidade Funcional aplicada aos módulos SIAGUH.",
    amostraModulos: "Ecrãs de Registo de Utente, Triagem e Internamento.",
    resManual: "100% de conformidade nas heurísticas aplicadas aos formulários e elementos de navegação.",
    relUsa: "(20-03-2026). Relatório: Testes de Usabilidade SIAGUH.",
    participantesDesc: "Membros da equipa e utilizadores externos simulando os perfis de Administrativo, Médico e Enfermeiro.",
    tarefasDesc: "Localização de utentes, registo de sinais vitais na triagem e consulta de previsões de IA.",
    resUsa: "O portal apresenta um nível robusto de usabilidade, facilitando a interação mesmo em cenários críticos de urgência hospitalar.",
    contactoTitulo: "III. Contacto e Solicitação de Informação Relativa ao Sítio Web",
    contactoTexto: "Para contactar, enviar sugestões ou solicitar informação adicional relativamente às funcionalidades do sistema SIAGUH desenvolvido pelo Grupo 8, utilize os contactos dos responsáveis:",
    responsaveisNomes: "João Martins, João Sacramento, Luís Franco e Pedro Antunes.",
    evidenciasTitulo: "IV. Outras Evidências",
    evidenciasTexto: "O Grupo 8 implementou uma arquitetura modular no backend (FastAPI) e frontend para garantir que futuras atualizações de acessibilidade possam ser integradas sem comprometer a escalabilidade do sistema.",
    denunciaTitulo: "V. Denúncia de Situações de Discriminação",
    denunciaTexto: "Sempre que uma pessoa com deficiência seja objeto de um tratamento menos favorável que consubstancie uma prática discriminatória, pode apresentar queixa nos termos da legislação vigente. O Instituto Nacional para a Reabilitação (INR, I.P.) disponibiliza os canais competentes para o efeito.",
    notaRodape: "A presente Declaração foi criada para o Projeto Integrador PRODIGI (Grupo 8 - 2026) em conformidade com o Decreto-Lei n.º 83/2018, de 19 de outubro.",
    seccaoIntro: "Declaração de Acessibilidade e Usabilidade. O Grupo 8 Sapos compromete-se a disponibilizar o sítio Web do sistema PRODIGI, Sistema de Gestão Hospitalar, em conformidade com a legislação vigente.",
    seccao1Voz: "Secção 1. Estado de conformidade. O sítio Web PRODIGI está plenamente conforme.",
    seccao2Voz: "Secção 2. Elaboração da presente declaração. Esta declaração foi atualizada em abril de 2026.",
    seccaoA_Voz: "Ponto A. Avaliações automáticas. Foi obtido um score elevado nas normas WCAG 2.1.",
    seccaoB_Voz: "Ponto B. Avaliações manuais. 100% de conformidade nas heurísticas aplicadas aos formulários.",
    seccaoC_Voz: "Ponto C. Testes de usabilidade. O portal apresenta um nível robusto de usabilidade em cenários críticos.",
    seccao3Voz: "Secção 3. Contacto. Utilize o e-mail grupo 8 underscore prodigi arroba exemplo ponto pt.",
    seccao4Voz: "Secção 4. Outras evidências. Implementada arquitetura modular para garantir escalabilidade e futuras atualizações.",
    seccao5Voz: "Secção 5. Denúncia. O Instituto Nacional para a Reabilitação disponibiliza canais para denúncia de discriminação."
  },

  // ==========================================
  // 9. PÁGINA: FAQS
  // ==========================================
  faqs: {
    titulo: "Perguntas Frequentes (FAQs)",
    subtitulo: "Encontre respostas rápidas para as dúvidas mais comuns sobre o funcionamento do sistema SIAGUH.",
    expandirTudo: "Expandir tudo",
    colapsarTudo: "Colapsar tudo",
    q1: "O que é o SIAGUH?",
    a1: "É o Sistema Integrado de Apoio à Gestão de Urgências Hospitalares, uma plataforma modular (SIAGUH) desenvolvida para gerir desde a entrada do utente até à sua alta ou internamento.",
    q2: "Os meus dados estão seguros?",
    a2: "Sim. O sistema utiliza autenticação robusta (JWT) e segue as normas do RGPD para garantir que apenas profissionais autorizados acedam aos dados clínicos.",
    q3: "Como é decidida a cor da minha pulseira?",
    a3: "O enfermeiro introduz os seus sinais vitais e sintomas no sistema. A nossa IA analisa esses dados em conjunto com os antecedentes patológicos do doente e sugere uma cor baseada no Protocolo de Manchester, mas a decisão final é sempre validada por um profissional de saúde.",
    q4: "O tempo de espera indicado é exato?",
    a4: "O tempo é uma estimativa calculada pela IA com base no histórico do hospital, quadro hospitalar e no número de doentes em espera no momento. Pode sofrer alterações se surgirem casos de emergência crítica (pulseiras vermelhas).",
    q5: "Como posso saber em que quarto estou internado?",
    a5: "Essa informação é gerida no módulo de internamentos, onde o sistema atribui automaticamente uma cama e serviço após a decisão médica.",
    q6: "Onde posso consultar as minhas prescrições?",
    a6: "As prescrições emitidas pelos médicos ficam registadas no seu histórico clínico dentro do SIAGUH e podem ser consultadas pelos profissionais que o acompanham.",
    q7: "Como recupero o meu acesso de funcionário?",
    a7: "Deve contactar o Administrador do sistema, que é o responsável pela gestão de contas e permissões no módulo de profissionais.",
    q8: "O sistema funciona em dispositivos móveis?",
    a8: "Sim, o SIAGUH possui uma aplicação Android dedicada para que os profissionais possam consultar dados e registar atos médicos em mobilidade."
  },

  // ==========================================
  // 10. PÁGINA: HOME (LANDING PAGE)
  // ==========================================
  home: {
    labelIntro: "Introdução",
    tituloPrincipal: "SIAGUH — Sistema Integrado de Apoio à Gestão de Urgências Hospitalares",
    subtituloPrincipal: "Plataforma de apoio à gestão hospitalar, urgências, internamentos e organização dos profissionais de saúde.",
    labelProjeto: "Projeto",
    valorProjeto: "Grupo 8 · PRODIGI",
    labelArea: "Área",
    valorArea: "Urgências e internamentos",
    labelTech: "Tecnologia",
    valorTech: "FastAPI · PostgreSQL · Docker",
    labelHospitais: "Hospitais",
    tituloHospitais: "Hospitais disponíveis e tempos de espera",
    subtituloHospitais: "Consulta rápida das unidades registadas no sistema.",
    statusDisponivel: "Disponível",
    labelEspera: "Tempo de espera",
    valorEsperaIndisponivel: "-- min",
    btnAnterior: "Ver hospitais anteriores",
    btnSeguinte: "Ver próximos hospitais",
    ariaPaginacao: "Navegação entre páginas de hospitais",
    ariaDots: "Indicador de página de hospitais",
    labelInfo: "Mais informações",
    tituloInfo: "Destaques e Informações",
    ariaCarrossel: "Destaques informativos do sistema",
    altSlide: "Informação de destaque número",
    ariaIrParaSlide: "Ir para o slide",
  },

  // ==========================================
  // 11. PÁGINA: LOGIN
  // ==========================================
  login: {
    tituloLogin: "Login",
    subtituloLogin: "Introduz as tuas credenciais para entrares no sistema.",
    tituloHospital: "Selecionar hospital",
    subtituloHospital: "Escolhe o hospital onde vais trabalhar nesta sessão.",
    labelPasso1: "Autenticação",
    labelPasso2: "Hospital",
    btnEntrar: "Entrar",
    erroLogin: "Erro ao tentar fazer login.",
    erroRole: "Função do utilizador não identificada.",
    erroHospitais: "Este utilizador não tem hospitais autorizados.",
    erroDestino: "Não foi possível determinar a página de destino.",
    ariaVoltar: "Voltar para a página inicial",
    ariaPassoHospital: "Credenciais corretas. Agora, selecione um hospital da lista abaixo.",
  },

  // ==========================================
  // 12. PÁGINA: POLÍTICA DE PRIVACIDADE
  // ==========================================
  politicaPrivacidade: {
    breadcrumb: "Política de Privacidade",
    tituloPrincipal: "Política de Privacidade — SIAGUH",
    notaLabel: "Nota:",
    notaTexto: "Este sistema foi desenvolvido para fins académicos pelo Grupo 8 (João Martins, João Sacramento, Luís Franco e Pedro Antunes).",
    s1Titulo: "1. Enquadramento Geral",
    s1Texto1: "Esta Política de Privacidade aplica-se ao",
    s1Texto2: "incluindo o portal web, aplicação móvel Android e sistemas de triagem, desenvolvidos pelo Grupo 8, no âmbito do Projeto Integrador de 2026.",
    s2Titulo: "2. Responsável pelo Tratamento e Encarregado de Proteção de Dados",
    s2Texto: "A entidade responsável pelo tratamento de dados é o Grupo 8, com supervisão académica no âmbito do projeto PRODIGI/SIAGUH.",
    s3Titulo: "3. Dados Pessoais Tratados",
    s3Intro: "O SIAGUH recolhe e trata dados necessários para a operação hospitalar segura:",
    lblDemog: "Dados Demográficos:",
    txtDemog: "Nome, data de nascimento, NIF, número de utente, localidade e contactos.",
    lblSaude: "Dados de Saúde:",
    txtSaude: "Sintomas, antecedentes clínicos, registos de triagem, atos médicos e prescrições.",
    lblIA: "Dados de IA:",
    txtIA: "Resultados do processamento de linguagem natural e algoritmos de previsão.",
    s4Titulo: "4. Finalidades e Fundamentos Jurídicos",
    s4Intro: "O tratamento de dados no SIAGUH, fundamenta-se na gestão e prestação de cuidados de saúde.",
    lblTriagem: "Triagem Clínica:",
    txtTriagem: "Utilização de IA para sugestão da cor da pulseira.",
    lblDecisao: "Apoio à Decisao:",
    txtDecisao: "Previsão de tempos de espera e gestão de camas.",
    lblSeguranca: "Segurança:",
    txtSeguranca: "Autenticação de profissionais via JWT.",
    s5Titulo: "5. Utilização de Inteligência Artificial no SIAGUH",
    s5Intro: "O SIAGUH integra um sistema de IA para apoio à triagem.",
    s5Item1: "A IA não decide de forma autónoma.",
    s5Item2: "O utilizador humano pode sempre validar ou ignorar.",
    s5Item3: "Os dados melhoram a precisão do atendimento.",
    s6Titulo: "6. Prazo de Conservação e Comunicação",
    lblConserva: "Conservação:",
    txtConserva: "Mantidos pelo período necessário à prestação de cuidados.",
    lblComunica: "Comunicação:",
    txtComunica: "Partilhados entre profissionais e entidades autorizadas.",
    s7Titulo: "7. Direitos dos Titulares",
    s7Intro: "Os utentes e profissionais gozam dos direitos previstos no RGPD.",
    lblDireito1: "Acesso e Retificação:",
    txtDireito1: "(historial clínico).",
    lblDireito2: "Oposição a Decisões Automatizadas:",
    txtDireito2: "Revisão por um humano.",
    lblDireito3: "Portabilidade:",
    txtDireito3: "Formato estruturado.",
    s8Titulo: "8. Atualização e Foro",
    s8Texto: "Esta política foi atualizada em 17 de abril de 2026.",
    v1: "Política de Privacidade SIAGUH. Secção 1. Enquadramento Geral.",
    v2: "Secção 2. Responsável pelo Tratamento.",
    v3: "Secção 3. Dados Pessoais Tratados.",
    v4: "Secção 4. Finalidades.",
    v5: "Secção 5. Utilização de Inteligência Artificial.",
    v6: "Secção 6. Conservação.",
    v7: "Secção 7. Direitos dos Titulares.",
    v8: "Secção 8. Foro."
  },

  // ==========================================
  // 13. PÁGINA: PERFIL DO FUNCIONÁRIO
  // ==========================================
  perfil: {
    titulo: "O Meu Perfil",
    sucessoGuardar: "Perfil atualizado com sucesso!",
    erroCarregar: "Não foi possível carregar os teus dados: ",
    erroSessao: "Utilizador não encontrado na sessão.",
    erroGuardar: "Erro ao guardar: ",
    aCarregar: "A carregar o teu perfil...",
    botaoGuardar: "Guardar Alterações",
    botaoGuardarLoading: "A guardar...",
    numFuncionario: "Nº Funcionário:",
    linkFotografia: "Link da Fotografia",
    placeholderFotografia: "https://...",
    telemovel: "Telemóvel",
    emailPessoal: "Email Pessoal",
    sobreMim: "Sobre Mim",
    placeholderBiografia: "Escreve aqui uma breve descrição sobre a tua experiência profissional...",
    segurancaAcesso: "Segurança de Acesso",
    nomeUtilizador: "Nome de Utilizador",
    novaPassword: "Nova Password",
    placeholderPassword: "(Deixar em branco para manter)"
  },

  doctor: {
    tituloPainel: 'Dashboard Médico',
    descricaoPainel: 'Prioridade, detalhe clínico completo, prescrição e decisão final.',
    menuKpis: 'KPIs',
    menuMedias: 'Tempos médios',
    menuFila: 'Fila por prioridade',
    menuEpisodios: 'Episódios triados',
    menuDetalhe: 'Detalhe completo',
    menuPrescricao: 'Prescrição',
    menuAlta: 'Alta / internamento',
    kpisTitulo: 'Resumo clínico',
    kpisDesc: 'Visão rápida dos episódios triados e estado atual.',
    episodiosTriados: 'Episódios triados',
    emEspera: 'Em espera',
    altasHoje: 'Altas hoje',
    internamentos: 'Internamentos',
    temposMedios: 'Tempos médios por cor',
    cor: 'Cor',
    tempoMedio: 'Tempo médio',
    filaPrioridade: 'Fila resumida por prioridade',
    placeholderPesquisa: 'Utente, cor, episódio...',
    episodios: 'Episódios',
    utente: 'Utente',
    espera: 'Espera',
    acao: 'Ação',
    atender: 'Atender',
    episodiosTriadosLista: 'Episódios triados',
    listaCompleta: 'Lista completa',
    episodio: 'Episódio',
    gravidade: 'Gravidade',
    abrirDetalhe: 'Abrir detalhe',
    detalheCompleto: 'Detalhe completo do episódio',
    alertas: 'Alertas',
    semAlertas: 'Sem alertas registados.',
    medicacaoAtiva: 'Medicação ativa',
    semMedicacao: 'Sem medicação ativa.',
    selecionaTriado: 'Seleciona um episódio triado.',
    prescricao: 'Prescrição',
    medicamento: 'Medicamento',
    dosagem: 'Dosagem',
    duracao: 'Duração',
    via: 'Via',
    fazerPrescricao: 'Fazer prescrição',
    altaInternamento: 'Alta ou internamento',
    destino: 'Destino',
    alta: 'Alta',
    destinoInternamento: 'Destino internamento',
    observacoes: 'Observações',
    confirmar: 'Confirmar',
  },

  nurse: {
    tituloPainel: 'Dashboard Enfermeiro',
    descricaoPainel: 'Fila de episódios, contexto clínico e triagem assistida.',
    menuFila: 'Fila sem triagem',
    menuTriagem: 'Abrir triagem',
    menuFicha: 'Ficha do utente',
    menuMedicacao: 'Medicação ativa',
    menuRegisto: 'Registar triagem',
    filaSemTriagem: 'Fila de episódios abertos sem triagem',
    placeholderPesquisa: 'Utente, NIF, episódio...',
    episodios: 'Episódios',
    episodio: 'Episódio',
    utente: 'Utente',
    entrada: 'Entrada',
    abrir: 'Abrir',
    abrirTriagem: 'Abrir episódio para triagem',
    verFicha: 'Ver ficha',
    verMedicacao: 'Ver medicação',
    selecionaFila: 'Seleciona um episódio na fila.',
    fichaUtente: 'Ficha do utente',
    nome: 'Nome',
    dataNascimento: 'Data nascimento',
    alergias: 'Alergias',
    abreEpisodioFicha: 'Abre um episódio para consultar a ficha.',
    medicacaoAtiva: 'Medicação ativa',
    lista: 'Lista',
    posologia: 'Posologia',
    inicio: 'Início',
    fim: 'Fim',
    registarTriagem: 'Registar triagem',
    tensao: 'Tensão',
    pulso: 'Pulso',
    temperatura: 'Temperatura',
    saturacao: 'Saturação',
    dor: 'Dor',
    sintomas: 'Sintomas',
    corSugerida: 'Cor sugerida',
    pedirSugestaoIa: 'Pedir sugestão IA',
    gravarTriagem: 'Gravar triagem',
  },

  receptionist: {
    tituloPainel: 'Dashboard Rececionista',
    descricaoPainel: 'Gestão de utentes e episódios de urgência.',
    menuPesquisar: 'Pesquisar utente',
    menuEpisodio: 'Abrir episódio',
    menuRecentes: 'Entradas recentes',
    pesquisarUtente: 'Pesquisar utente',
    novoUtente: 'Novo utente',
    pesquisaRapida: 'Pesquisa rápida',
    placeholderPesquisa: 'Nome, NIF, número de utente...',
    utentes: 'Utentes',
    nome: 'Nome',
    nif: 'NIF',
    sexo: 'Sexo',
    verFicha: 'Ver ficha',
    nenhumUtente: 'Nenhum utente encontrado.',
    dataNascimento: 'Data nascimento',
    telefone: 'Telefone',
    email: 'Email',
    morada: 'Morada',
    fichaBase: 'Ficha base do utente',
    selecionaUtente: 'Selecione um utente na pesquisa.',
    abrirEpisodioBtn: 'Abrir episódio',
    motivo: 'Motivo',
    observacao: 'Observação',
    utente: 'Utente',
    selecionaPrimeiro: 'Selecione um utente primeiro.',
    episodiosRecentes: 'Episódios recentes',
    pesquisaEpisodios: 'Pesquisa rápida de episódios',
    placeholderEpisodios: 'Pesquisar por nome ou estado...',
    entrada: 'Entrada',
    estado: 'Estado',
    estadoAberto: 'Aberto',
    semEpisodios: 'Sem episódios recentes.',
    erroCarga: 'Erro ao carregar dados do servidor.',
    erroProcessamento: 'Erro ao processar dados do utente.',
    erroEpisodio: 'Erro ao abrir episódio.',
    sucessoCriar: 'Utente criado com sucesso.',
    sucessoUpdate: 'Utente atualizado com sucesso.',
    sucessoEpisodio: 'Episódio aberto com sucesso.',
    ariaSidebar: "Navegação lateral do rececionista",
    ariaToggleSidebar: "Alternar menu lateral",
    ariaPerfil: "Ver meu perfil"
  }

};